### ISSUE TITLE
Diagrama de clases Architec - ISAI 

### ISSUE THREAD

**Issue by isaireyesp1** [SistemasTecTlaxiaco/actividad-3-practica-architect-isaireyesp1#1]
[architec.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-isaireyesp1/files/12555311/architec.pdf)

**Comment by DaisyOrtiz2** [comment]
portada 22
procedimiento 15
figuras 15
conclusion 22
14/20

**Comment by DaisyOrtiz2** [comment]
portada 22
procedimiento 25
figura 22
conclusion 22
18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
